import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const variant = process.argv[2];
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
const errs = [];
p.on('pageerror', e => errs.push('PAGEERROR ' + e.message));
p.on('console', m => { if (m.type() === 'error') errs.push('CONSOLE ' + m.text()); });
await p.goto('file://' + process.cwd() + '/' + variant + '/preview.html');
await p.waitForTimeout(1500);
await p.screenshot({ path: `${variant}-1-home.png` });
await p.click('[data-go="lift"]'); await p.waitForTimeout(400);
await p.screenshot({ path: `${variant}-2-lift.png` });
await p.click('#b-tune'); await p.waitForTimeout(300);
await p.screenshot({ path: `${variant}-3-tune.png` });
await p.click('[data-start="lift"]'); await p.waitForTimeout(4200);
await p.screenshot({ path: `${variant}-4-run.png` });
await p.waitForTimeout(2500);
await p.screenshot({ path: `${variant}-5-run2.png` });
await p.click('#endbtn'); await p.waitForTimeout(400);
await p.click('[data-go="mode"]'); await p.waitForTimeout(300);
await p.click('[data-go="breathe"]'); await p.waitForTimeout(300);
await p.screenshot({ path: `${variant}-6-breathe.png` });
await p.click('#s-breathe [data-go="mode"]'); await p.waitForTimeout(300);
await p.click('[data-go="stats"]'); await p.waitForTimeout(300);
await p.screenshot({ path: `${variant}-7-stats.png` });
// hold-check: force the longest phase word on screen
await p.evaluate(() => { const w=document.querySelector('#word span'); });
console.log(variant, 'errors:', errs.length ? errs.join(' | ') : 'none');
await b.close();
